// <auto-generated />
using System;
using EntityLINQ;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace _8_EFDemo_Migrations.Migrations
{
    [DbContext(typeof(LearningModelContainer))]
    [Migration("20230924180911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntityLINQ.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentGroupSet");
                });

            modelBuilder.Entity("EntityLINQ.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubjectTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectTypeId");

                    b.ToTable("SubjectSet");
                });

            modelBuilder.Entity("EntityLINQ.SubjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParentSubjectTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentSubjectTypeId");

                    b.ToTable("SubjectTypeSet");
                });

            modelBuilder.Entity("StudentGroupSubject", b =>
                {
                    b.Property<int>("StudentGroupsId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("integer");

                    b.HasKey("StudentGroupsId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("StudentGroupSubject");
                });

            modelBuilder.Entity("EntityLINQ.Subject", b =>
                {
                    b.HasOne("EntityLINQ.SubjectType", "SubjectType")
                        .WithMany()
                        .HasForeignKey("SubjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectType");
                });

            modelBuilder.Entity("EntityLINQ.SubjectType", b =>
                {
                    b.HasOne("EntityLINQ.SubjectType", "ParentSubjectType")
                        .WithMany("ChildSubjectTypes")
                        .HasForeignKey("ParentSubjectTypeId");

                    b.Navigation("ParentSubjectType");
                });

            modelBuilder.Entity("StudentGroupSubject", b =>
                {
                    b.HasOne("EntityLINQ.StudentGroup", null)
                        .WithMany()
                        .HasForeignKey("StudentGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLINQ.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLINQ.SubjectType", b =>
                {
                    b.Navigation("ChildSubjectTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
