FROM alpine:3.11.5

RUN apk add --no-cache nginx && mkdir -p /run/nginx

#RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.11/main nginx=1.16.1-r6 \
#&& mkdir -p /run/nginx

#ENV NGINX_VERSION 1.16.1-r6
#RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.11/main nginx=${NGINX_VERSION} \
#&& mkdir -p /run/nginx

EXPOSE 80

COPY custom.conf /etc/nginx/conf.d/

# This will test the configuration for syntax correctness and output any errors.
# If the config is incorrect, the Docker build will fail, and you'll see the error message.
RUN nginx -t

COPY . /opt/

CMD ["nginx", "-g", "daemon off;"]
